#### Data Collection and Acquisition

In [69]:
import yfinance as yf
import pandas as pd

df_yf=yf.download(
    'AAPL',
    start='2015-01-01',
    end='2025-10-25',
    interval='3mo',
    auto_adjust=False,
    progress=False

)
df_yf

Price,Adj Close,Close,High,Low,Open,Volume
Ticker,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL
Date,,,,,,
2015-01-01,27.611830,31.107500,33.400002,26.157499,27.847500,14321762800
2015-04-01,27.943590,31.357500,33.634998,30.775000,31.205000,11315577200
2015-07-01,24.675539,27.575001,33.242500,23.000000,31.725000,15486588000
2015-10-01,23.654613,26.315001,30.955000,26.205000,27.267500,11140271600
2016-01-01,24.597677,27.247499,27.605000,23.097500,25.652500,11315040800
2016-04-01,21.692797,23.900000,28.097500,22.367500,27.195000,10210211600
2016-07-01,25.808607,28.262501,29.045000,23.592501,23.872499,9135694800
2016-10-01,26.584206,28.955000,29.672501,26.020000,28.177500,8068964000
2017-01-01,33.143627,35.915001,36.125000,28.690001,28.950001,6798876000
2017-04-01,33.370743,36.005001,39.162498,35.014999,35.927502,6845856000
2017-07-01,35.858402,38.529999,41.235001,35.602501,36.220001,7053820000
2017-10-01,39.528603,42.307499,44.299999,38.115002,38.564999,6544554000
2018-01-01,39.330799,41.945000,45.875000,37.560001,42.540001,9205205600
2018-04-01,43.570198,46.277500,48.549999,40.157501,41.660000,7259020400
2018-07-01,53.338356,56.435001,57.417500,45.855000,45.955002,7091929200
2018-10-01,37.401894,39.435001,58.367500,36.647499,56.987499,10599989600
2019-01-01,45.196377,47.487499,49.422501,35.500000,38.722500,7806437600
2019-04-01,47.294716,49.480000,53.827499,42.567501,47.910000,7043172000
2019-07-01,53.725677,55.992500,56.605000,48.145000,50.792500,6790001600
2019-10-01,70.708092,73.412498,73.492500,53.782501,56.267502,6615331600
2020-01-01,61.414410,63.572498,81.962502,53.152500,74.059998,12233722000
2020-04-01,88.313133,91.199997,93.095001,59.224998,61.625000,9314610800
2020-07-01,112.447678,115.809998,137.979996,89.144997,91.279999,10975589400
2020-10-01,129.069946,132.690002,138.789993,107.320000,117.639999,7339933400
2021-01-01,119.022476,122.150002,145.089996,116.209999,133.520004,6724535800
2021-04-01,133.652695,136.960007,137.410004,122.250000,123.660004,5208382400
2021-07-01,138.317596,141.500000,157.259995,135.759995,136.600006,5178413000
2021-10-01,173.836426,177.570007,182.130005,138.270004,141.899994,5700874900
2022-01-01,171.188156,174.610001,182.940002,150.100006,177.830002,5916762400
2022-04-01,134.211456,136.720001,178.490005,129.039993,174.029999,5837935700
2022-07-01,135.863602,138.199997,176.149994,135.660004,136.039993,5042087800
2022-10-01,127.910858,129.929993,157.500000,125.870003,138.210007,5268718600
2023-01-01,162.606735,164.899994,165.000000,124.169998,130.279999,4271118000
2023-04-01,191.564499,193.970001,194.479996,159.779999,164.270004,3542524400
2023-07-01,169.320633,171.210007,198.229996,167.619995,193.779999,3656594800
2023-10-01,190.662460,192.529999,199.619995,165.669998,171.220001,3335649700
2024-01-01,170.040359,171.479996,196.380005,168.490005,187.149994,3782196100
2024-04-01,209.118286,210.619995,220.199997,164.080002,171.190002,4300607500
2024-07-01,231.652496,233.000000,237.229996,196.000000,212.089996,3507864500
2024-10-01,249.259933,250.419998,260.100006,219.710007,229.520004,2800240400
2025-01-01,221.344254,222.130005,250.000000,208.419998,248.929993,3177688200
2025-04-01,204.669022,205.169998,225.190002,169.210007,219.809998,3903456100
2025-07-01,254.341354,254.630005,257.600006,201.500000,206.669998,3563551100
2025-10-01,262.820007,262.820007,265.290009,244.000000,255.039993,840290299

In [70]:
from fredapi import Fred
import pandas as pd
import matplotlib.pyplot as plt

fred = Fred(api_key='3dd37ba3122e1228a5bacd7f8c6f3775')

sp500 = fred.get_series('SP500',
                        observation_start='2015-01-01',
                        observation_end='2025-12-31')


sp500 = sp500.rename('S&P 500 Index')
sp500.to_csv('sp500_2015_2025.csv')

sp500

2015-10-26    2071.18
2015-10-27    2065.89
2015-10-28    2090.35
2015-10-29    2089.41
2015-10-30    2079.36
               ...
2025-10-20    6735.13
2025-10-21    6735.35
2025-10-22    6699.40
2025-10-23    6738.44
2025-10-24    6791.69
Name: S&P 500 Index, Length: 2610, dtype: float64